parameters:
    paypal.client_id: 'AUM5mwwUWLZ8fMbAdqfN9BcIOpl4K3bnem6MrfgleZ1z3ahP6BRm4PrKIfcwy84qM3kLvx2ZZUN5-6ce'
    paypal.client_secret: 'ELQpfXKa5OSBJWiC82xmxyujwzBlh9pAOZS6-Ncm6hL-_vJYNb8WO4J5_q8fu5DnKx-pIQvIF3WEWBaV'
